services:
    # outside services
    xm_user_admin.paginator: "@knp_paginator"

    # user admin
    xm_user_admin.filter.user:
        class: XM\UserAdminBundle\Component\Filter\UserFilter
        arguments: ["@request_stack", "@session", "@form.factory", "@xm_user_admin.paginator"]
    xm_user_admin.twig_extension.user_role:
        class: XM\UserAdminBundle\Twig\Extension\UserRoleExtension
        arguments: ['%xm_user_admin.roles%']
        public: false
        tags:
            - { name: twig.extension }